---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: cloudsql-instance-credentials
type: Opaque
data:
  db-user: {{ .Values.adminer.env.dbUsername | b64enc | quote }}
  db-pass: {{ .Values.adminer.env.dbPassword | b64enc | quote }}
  credentials.json: {{ .Files.Get "credentials.json" | b64enc | quote }}
