---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "rediscommander.fullname" . }}
data:
  redis-hosts: {{ .Values.rediscommander.env.redisHosts }}
