---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "email.fullname" . }}
  namespace: {{ .Values.email.namespace }}
data:
  my-domain: {{ .Values.email.env.myDomain }}
