---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.email.name }}
  namespace: {{ .Values.email.namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.email.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    tier: {{ .Values.email.labels.tier }}
spec:
  type: {{ .Values.email.service.type }}
  {{- if .Values.email.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.email.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.email.externalPortSMTP }}
    targetPort: {{ .Values.email.internalPortSMTP }}
    protocol: TCP
    name: smtp
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.email.name }}"
    release: {{ .Release.Name }}
