# Default values for email relay.

email:
  name: email
  replicaCount: 1
  labels:
    tier: service
  externalPortSMTP: 25
  internalPortSMTP: 25
  service:
    type: ClusterIP
  env:
    myDomain: stevenaldinger.com
    smtpUser: no-reply@stevenaldinger.com
    smtpPass: my-sensitive-password!
  image:
    repository: gcr.io/steven-aldinger/demo-app/email/relay
    version: "0.0.1"
    pullPolicy: IfNotPresent
  # progressDeadlineSeconds: 60
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
    readinessProbe: false
    livelinessProbe: false
