---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "openvpn.fullname" . }}
  namespace: {{ .Values.openvpn.namespace }}
type: Opaque
data:
  ca-passphrase: {{ .Values.openvpn.env.caPassphrase | b64enc | quote }}
