---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: vpn-conf
  namespace: {{ .Values.openvpn.namespace }}
data:
  openvpn.conf: |
{{ .Files.Get .Values.openvpn.configFile | indent 4 }}
