---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openvpn.name }}
  namespace: {{ .Values.openvpn.namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.openvpn.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    tier: {{ .Values.openvpn.labels.tier }}
spec:
  type: {{ .Values.openvpn.service.type }}
  {{- if .Values.openvpn.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.openvpn.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.openvpn.externalPortDNS }}
    targetPort: {{ .Values.openvpn.internalPortDNS }}
    protocol: UDP
    name: dns
  - port: {{ .Values.openvpn.externalPortUDP }}
    targetPort: {{ .Values.openvpn.internalPortUDP }}
    protocol: UDP
    name: udp
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.openvpn.name }}"
    release: {{ .Release.Name }}
