# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   labels:
#     app: {{ template "name" . }}
#     chart: {{ .Chart.Name }}-{{ .Chart.Version }}
#     heritage: {{ .Release.Service }}
#     release: {{ .Release.Name }}
#   name: {{ template "gui.fullname" . }}
# type: Opaque
# data:
#   node-env: {{ .Values.gui.env.nodeEnv | b64enc | quote }}
